ReportSpecific:
  report_week_number: 43
  report_year: 2016
  report_title: "%REPORT_YEAR Week %WEEK_NUMBER (%WEEK_START-%WEEK_END)"

Trello:
  board_id: AhXqJnjl
  stat_enabled: true
  # to generate your Trello developer key visit https://trello.com/1/appKey/generate
  api_key: PUT_YOUR_KEY_HERE
  # to get your token read https://trello.com/docs/gettingstarted/index.html#getting-a-token-from-a-user
  # or just open the following link in the browser (don't forget to change SUBSTITUE_WITH_YOUR_DEV_KEY with your developer_key
  # https://trello.com/1/authorize?key=SUBSTITUTE_WITH_YOUR_DEV_KEY&name=coscious-life-generator&expiration=never&response_type=token
  user_oauth_token: PUT_YOUR_OAUTH_TOKEN_HERE
  list_done_names: Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
  list_notes_name: Notes
  naming_rules_file: configs/naming_rules_trello.txt
  past_tense_rules_file: configs/past_tense_rules.txt
  lists_stats_graph_filename: lists_stats.png
  list_stats_graph_tag: |
      <img style="max-height:300px;vertical-align:middle;padding:5px" src="{}">
  list_group_separator_regexp: \s*\*\*\*.*\*\*\*\s*
  # values before week 36
  # title_planned_regexp: ^.*\((-?\d+(\.\d+)?)\).*$
  # title_done_cucumbers_regexp: ^.*\((-?\d+(\.\d+)?)\).*$
  # title_done_pomodoros_regexp: ^.*\[(\d+)\]\s*$
  title_planned_regexp: ^.*\((?:\d+(?:\.\d+)?\/)?(\d+(?:\.\d+)?)\).*$
  title_done_cucumbers_regexp: ^.*\((\d+(?:\.\d+)?)\/\d+(?:\.\d+)?\).*$
  title_done_pomodoros_regexp: ^\s*(\d+)\s*✓.*$
  title_clean_regexp: (^\s*\d+\s*✓\s*|\(\d+(\.\d+)?\/?\d*(\.\d+)?\)|\[\d+\]\s*)

Files:
  naming_rules_file: configs/naming_rules.txt
  constant_sections_file: configs/constant_sections.txt
  pic_dir: "/Users/olegshevelev/Dropbox/Productivity/Reports Unfinished/%REPORT_YEAR Week %WEEK_NUMBER pics"
  jiffy_report_file: "/Users/olegshevelev/Dropbox/Productivity/Reports Unfinished/jiffy/jiffy week %WEEK_NUMBER.csv"
  out_html_report_file: "/Users/olegshevelev/Dropbox/Productivity/Reports Unfinished/%REPORT_YEAR Week %WEEK_NUMBER.html"

Columns:
  column_name_project: Project
  column_name_task: Task
  column_name_extra: Note
  column_name_start_time: Start time
  column_name_stop_time: Stop time

Zotero:
    # Your personal library ID is available at https://www.zotero.org/settings/keys,
    # in the section Your userID for use in API calls
    library_id: PUT_YOUR_LIBRARY_ID_HERE
    library_type: user
    # to generate a new api_key https://www.zotero.org/settings/keys/new
    api_key: PUT_YOUR_API_KEY_HERE
    read_tag: Done
    naming_rules_file: configs/naming_rules_articles.txt

Pocket:
    consumer_key: PUT_YOUR_CONSUMER_KEY_HERE
    # to get access token, copy paste consumer key here
    # http://reader.fxneumann.de/plugins/oneclickpocket/auth.php?consumer_key=46352-1fffd94875bbf8016f9f8bdc&token=aa192b77-add3-c74f-5e3a-34b392
    # and press the button to obtain the access to your data
    access_token: PUT_YOUR_ACCESS_TOKEN_HERE
    naming_rules_file: configs/naming_rules_articles.txt

Html:
  before_report: |
    <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <style>
    img.book {max-height:80px;vertical-align:middle;padding:5px}
    img.photo {max-height:320px;vertical-align:middle;padding:5px}
    .stats {color: lightgray}
    .level1 {font-weight: bold;font-size:130%;padding:10px}
    .level2 {font-weight: bold;font-size:120%;padding:10px}
    .level3 {font-weight: bold;font-size:110%;padding:5px}
    .level4 {font-weight: bold;padding:5px}
    .level5 {padding:5px}
    a {color: #0254EB}
    a:visited {color: #0254EB}
    a.morelink {text-decoration:none;outline: none;}
    .morecontent span {display: none;}
    </style>
    </head>
    <body><div style="background:white;width:800px;right: 0;left: 0;margin-right: auto;margin-left: auto;">
  after_report: |
    <li class=level4>Time for writing this report: X:X (template 0:10, draft X:X, the rest is editing).</li></div>
    </body>
    <script>$(document).ready(function() {
        var showChar = 400;
        var ellipsestext = "...";
        var moretext = "more";
        var lesstext = "less";
        $(''.more').each(function() {
            var content = $(this).html();
            if(content.length > showChar) {
                var c = content.substr(0, showChar);
                var h = content.substr(showChar-1, content.length - showChar);
                var html = c + '<span class="moreelipses">'+ellipsestext+'</span>&nbsp;<span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">'+moretext+'</a></span>';
                $(this).html(html);
            }
        });
        $(".morelink").click(function(){
            if($(this).hasClass("less")) {
                $(this).removeClass("less");
                $(this).html(moretext);
            } else {
                $(this).addClass("less");
                $(this).html(lesstext);
            }$(this).parent().prev().toggle();
            $(this).prev().toggle();return false;
        });
    });
    </script></html>'
