Report:
  report_title: "%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE (%PERIOD_START-%PERIOD_END)"
  pic_dir: "OUTPUT_PATH_TO_YOUR_REPORT/%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE pics"

ConstantSection:
  filename: configs/constant_sections.txt

Toggl:
  enabled: False
  auth_token: ADD_YOUR_AUTH_TOKEN_HERE
  entries_endpoint: "https://www.toggl.com/api/v8/time_entries?start_date={}&end_date={}"
  projects_endpoint: "https://www.toggl.com/api/v8/workspaces/YOU_WORKSPACE_ID_HERE/projects" # call https://www.toggl.com/api/v8/workspaces
  tag_order_filename: configs/tag_order_toggl.txt
  naming_rules_file: configs/naming_rules_toggl.txt
  past_tense_rules_file: configs/past_tense_rules.txt

Zotero:
  enabled: False
  # Your personal library ID is available at https://www.zotero.org/settings/keys,
  # in the section Your userID for use in API calls
  library_id: PUT_YOUR_LIBRARY_ID_HERE
  library_type: user
  # to generate a new api_key https://www.zotero.org/settings/keys/new
  api_key: PUT_YOUR_API_KEY_HERE
  read_tag: Done
  naming_rules_file: configs/naming_rules_articles.txt

Pocket:
  enabled: False
  consumer_key: PUT_YOUR_CONSUMER_KEY_HERE
  # to get access token, copy paste consumer key here
  # http://reader.fxneumann.de/plugins/oneclickpocket/auth.php?consumer_key=46352-1fffd94875bbf8016f9f8bdc&token=aa192b77-add3-c74f-5e3a-34b392
  # and press the button to obtain the access to your data
  access_token: PUT_YOUR_ACCESS_TOKEN_HERE
  naming_rules_file: configs/naming_rules_articles.txt

MarkdownGenerator:
  out_md_report_file: "OUTPUT_PATH_TO_YOUR_REPORT/%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE.md"
  before_report:
  after_report: |
    **Time for writing this report: X:X.**