Report:
  report_title: "%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE (%PERIOD_START-%PERIOD_END)"
  pic_dir: "/Users/olegshevelev/Dropbox/Productivity/Reports Unfinished/%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE pics"

ConstantSection:
  filename: configs/constant_sections.txt

SummaryExtender:
  summary_path: Overview/Summary

Toggl:
  enabled: False
  auth_token: ADD_YOUR_AUTH_TOKEN_HERE
  entries_endpoint: "https://www.toggl.com/api/v8/time_entries?start_date={}&end_date={}"
  projects_endpoint: "https://www.toggl.com/api/v8/workspaces/YOU_WORKSPACE_ID_HERE/projects" # call https://www.toggl.com/api/v8/workspaces
  tag_order_filename: configs/tag_order_toggl.txt
  naming_rules_file: configs/naming_rules_toggl.txt
  past_tense_rules_file: configs/past_tense_rules.txt

JawboneSleep:
  enabled: False
  auth_token: ADD_YOUR_AUTH_TOKEN_HERE # see https://jawbone.com/up/developer/authentication
  endpoint: "https://jawbone.com/nudge/api/v.1.1/users/@me/sleeps?start_time={}&end_time={}"
  sleep_by_days_graph_file: sleep_by_days.png
  asleep_by_days_graph_file: asleep_by_days.png
  naming_rules_file: configs/naming_rules_jawbone.txt
  graph_tag: |
      <img style="max-height:300px;vertical-align:middle;padding:5px" src="{}">

JawboneMoves:
  enabled: False
  auth_token: ADD_YOUR_AUTH_TOKEN_HERE # see https://jawbone.com/up/developer/authentication
  endpoint: "https://jawbone.com//nudge/api/v.1.1/users/@me/moves?start_time={}&end_time={}"
  steps_by_days_graph_file: steps_by_days.png
  activity_by_days_graph_file: activity_by_days.png
  naming_rules_file: configs/naming_rules_jawbone.txt
  graph_tag: |
      <img style="max-height:300px;vertical-align:middle;padding:5px" src="{}">

Zotero:
  enabled: False
  # Your personal library ID is available at https://www.zotero.org/settings/keys,
  # in the section Your userID for use in API calls
  library_id: PUT_YOUR_LIBRARY_ID_HERE
  library_type: user
  # to generate a new api_key https://www.zotero.org/settings/keys/new
  api_key: PUT_YOUR_API_KEY_HERE
  read_tag: Done
  naming_rules_file: configs/naming_rules_articles.txt

Pocket:
  enabled: False
  consumer_key: PUT_YOUR_CONSUMER_KEY_HERE
  # to get access token, copy paste consumer key here
  # http://reader.fxneumann.de/plugins/oneclickpocket/auth.php?consumer_key=46352-1fffd94875bbf8016f9f8bdc&token=aa192b77-add3-c74f-5e3a-34b392
  # and press the button to obtain the access to your data
  access_token: PUT_YOUR_ACCESS_TOKEN_HERE
  naming_rules_file: configs/naming_rules_articles.txt

HtmlGenerator:
  out_html_report_file: "/Users/olegshevelev/Dropbox/Productivity/Reports Unfinished/%REPORT_YEAR %PERIOD_TYPE%PERIOD_VALUE.html"
  before_report: |
    <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <style>
    img.book {max-height:80px;vertical-align:middle;padding:5px}
    img.photo {max-height:320px;vertical-align:middle;padding:5px}
    .stats {color: lightgray}
    .level1 {font-weight: bold;font-size:130%;padding:10px}
    .level2 {font-weight: bold;font-size:120%;padding:10px}
    .level3 {font-weight: bold;font-size:110%;padding:5px}
    .level4 {font-weight: bold;padding:5px}
    .level5 {padding:5px}
    a {color: #0254EB}
    a:visited {color: #0254EB}
    a.morelink {text-decoration:none;outline: none;}
    .morecontent span {display: none;}
    </style>
    </head>
    <body><div style="background:white;width:800px;right: 0;left: 0;margin-right: auto;margin-left: auto;">
  after_report: |
    <li class=level4>Time for writing this report: X:X (template 0:10, draft X:X, the rest is editing).</li></div>
    </body>
    <script>$(document).ready(function() {
        var showChar = 400;
        var ellipsestext = "...";
        var moretext = "more";
        var lesstext = "less";
        $(''.more').each(function() {
            var content = $(this).html();
            if(content.length > showChar) {
                var c = content.substr(0, showChar);
                var h = content.substr(showChar-1, content.length - showChar);
                var html = c + '<span class="moreelipses">'+ellipsestext+'</span>&nbsp;<span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">'+moretext+'</a></span>';
                $(this).html(html);
            }
        });
        $(".morelink").click(function(){
            if($(this).hasClass("less")) {
                $(this).removeClass("less");
                $(this).html(moretext);
            } else {
                $(this).addClass("less");
                $(this).html(lesstext);
            }$(this).parent().prev().toggle();
            $(this).prev().toggle();return false;
        });
    });
    </script></html>'
